version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: antoninabychkova
      POSTGRES_PASSWORD: 5021
      POSTGRES_DB: tododb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U antoninabychkova -d tododb"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://antoninabychkova:5021@db:5432/tododb
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana    # добавить volume
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # зафиксировать пароль
    depends_on:
      - prometheus

volumes:
  pgdata:
  grafana-data: